Vagrant.configure("2") do |config|
  # Настройка менеджера
  config.vm.define "manager01" do |manager|
    manager.vm.box = "ubuntu/bionic64" # Указываем образ Ubuntu
    manager.vm.network "private_network", type: "dhcp" # Настройка сети

    manager.vm.provider "virtualbox" do |vb|
      vb.memory = "4096" # Установите объем памяти в МБ
    end
    config.vm.synced_folder "./local_folder", "/vagrant_data"
    manager.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y docker.io
      systemctl start docker
      systemctl enable docker
      docker swarm init --advertise-addr $(hostname -i | awk '{print $1}') # Инициализация Docker Swarm
      docker swarm join-token -q worker > /vagrant_data/token_swarm.txt
      hostname -I | awk '{print $2}' > /vagrant_data/manager-ip.txt
    SHELL
  end

  # Настройка первого воркера
  config.vm.define "worker01" do |worker|
    worker.vm.box = "ubuntu/bionic64"
    worker.vm.network "private_network", type: "dhcp"
    config.vm.synced_folder "./local_folder", "/vagrant_data"
    
    worker.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y docker.io
      systemctl start docker
      systemctl enable docker
    SHELL

    worker.vm.provision "shell", inline: <<-SHELL
      # Получение токена для подключения к swarm
      TOKEN=$(cat /vagrant_data/token_swarm.txt)
      sudo docker swarm join --token $TOKEN $(/vagrant_data/manager-ip.txt):2377 # Присоединение к swarm
    SHELL
  end

  # Настройка второго воркера
  config.vm.define "worker02" do |worker|
    worker.vm.box = "ubuntu/bionic64"
    worker.vm.network "private_network", type: "dhcp"
    config.vm.synced_folder "./local_folder", "/vagrant_data"
    
    worker.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y docker.io
      systemctl start docker
      systemctl enable docker
    SHELL

    worker.vm.provision "shell", inline: <<-SHELL
      # Получение токена для подключения к swarm
      TOKEN=$(cat /vagrant_data/token_swarm.txt)
      sudo docker swarm join --token $TOKEN $(/vagrant_data/manager-ip.txt):2377 # Присоединение к swarm
    SHELL
  end
end
